### ISSUE TITLE
USER STORY: Publish a poll

### ISSUE THREAD

**Issue by nfepb** [nfepb/First-Agile-Project#6]
In order to **automatically hide the poll** as a **administrator**, I can **pick the expiry date while publishing the poll**.

## Acceptance Criteria:

* The poll should disappear for the users at 11:59pm.
* The real estate of the poll should be reserved on the home page. A message that says "Stay tuned, a new poll is coming soon" should be displayed if no poll is displayed.
* The admin expiry date should be at least 3 days after the current date.

## Tasks:

- [ ] Update the admin module view: the poll design (HTML & CSS) to include date picker
- [ ] Update the website view: show "Stay tuned, a new poll is coming soon"
- [ ] Create JavaScript function to validate the expiry date is at least after 3 days 
- [ ] Create a job to check expired polls everyday after 11:59pm and hide them
- [ ] Update the controller function
- [ ] Update unit test scripts
- [ ] Test the functionality

**Comment by nfepb** [comment]
User Story | Story Point Estimation | Assumptions/rationale
-- | -- | --
In order to provide my opinion with regards to a certain running topic or event as a user, I can select and submit an answer from the poll | 3 | We need to create the module and the various files: view, controller and modelWe need to create the design for the poll
In order to provide anonymous feedback as a user, I can choose to hide my identity in the poll response | 1 | Simple implementation as we just need to adjust the existing model, view and controller.
In order to provide additional thoughts beyond the response options as a user, I can add a comment before I submit my poll response. | 2 | Might require more effort than the previous story as we are adding a comment text area, which might require a considerable change in the design.
In order to collect users feedback, as an administrator, I can publish a poll | 3 | We need to create the module and the various files: view, controller and model.We need to create the design for the poll
In order to automatically hide the poll as an administrator, I can pick the expiry date while publishing the poll | 5 | We need to do major design changes on the home page and the administrator sideWe need to create a scheduled job to run at 11:59 PM to check for expired pollsWe need to adjust the view, the model and the contorller.
